/**
 * Generated by GitHub Copilot Agent
 * Issue: #generate-tests-for-payment-audit
 * Date: 2025-12-15
 * NOTE: This test was auto-generated. Please review and modify as needed.
 */
package com.alok.payment.paymentprocessor.integration;

import com.alok.payment.paymentprocessor.model.PaymentAudit;
import com.alok.payment.paymentprocessor.model.PaymentStatus;
import com.alok.payment.paymentprocessor.repository.PaymentAuditRepository;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.DisplayName;
import org.springframework.beans.factory.annotation.Autowired;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;

@DisplayName("PaymentAuditRepository Integration Tests")
class PaymentAuditRepositoryIT extends AbstractIntegrationTest {

    @Autowired
    private PaymentAuditRepository auditRepository;

    @Test
    @DisplayName("Should save and retrieve payment audit from database")
    void testSaveAndRetrieveAudit() {
        PaymentAudit audit = new PaymentAudit(
            "TEST-AUDIT-TXN-001",
            "PAYMENT_CREATED",
            null,
            PaymentStatus.PENDING,
            "ACC001",
            "ACC002",
            new BigDecimal("1500.00"),
            "USD",
            "SYSTEM",
            "Payment initiated for audit test"
        );

        PaymentAudit saved = auditRepository.save(audit);

        assertNotNull(saved.getId());
        assertEquals("TEST-AUDIT-TXN-001", saved.getTransactionId());
        assertEquals("PAYMENT_CREATED", saved.getAction());

        // Retrieve and verify
        Optional<PaymentAudit> retrieved = auditRepository.findById(saved.getId());
        assertTrue(retrieved.isPresent());
        assertEquals("ACC001", retrieved.get().getFromAccount());
        assertEquals(PaymentStatus.PENDING, retrieved.get().getNewStatus());
    }

    @Test
    @DisplayName("Should find audit records by transaction ID")
    void testFindByTransactionId() {
        // Create multiple audit records for same transaction
        PaymentAudit audit1 = new PaymentAudit(
            "TEST-AUDIT-TXN-002",
            "PAYMENT_CREATED",
            null,
            PaymentStatus.PENDING,
            "ACC001",
            "ACC002",
            new BigDecimal("2000.00"),
            "USD",
            "SYSTEM",
            "Payment created"
        );
        auditRepository.save(audit1);

        PaymentAudit audit2 = new PaymentAudit(
            "TEST-AUDIT-TXN-002",
            "STATUS_CHANGE",
            PaymentStatus.PENDING,
            PaymentStatus.PROCESSING,
            "ACC001",
            "ACC002",
            new BigDecimal("2000.00"),
            "USD",
            "SYSTEM",
            "Status changed to PROCESSING"
        );
        auditRepository.save(audit2);

        List<PaymentAudit> audits = auditRepository.findByTransactionId("TEST-AUDIT-TXN-002");

        assertNotNull(audits);
        assertEquals(2, audits.size());
        assertTrue(audits.stream().allMatch(a -> a.getTransactionId().equals("TEST-AUDIT-TXN-002")));
    }

    @Test
    @DisplayName("Should find audit records by action")
    void testFindByAction() {
        PaymentAudit audit = new PaymentAudit(
            "TEST-AUDIT-TXN-003",
            "PAYMENT_COMPLETED",
            PaymentStatus.PROCESSING,
            PaymentStatus.COMPLETED,
            "ACC001",
            "ACC002",
            new BigDecimal("500.00"),
            "USD",
            "SYSTEM",
            "Payment completed successfully"
        );
        auditRepository.save(audit);

        List<PaymentAudit> audits = auditRepository.findByAction("PAYMENT_COMPLETED");

        assertNotNull(audits);
        assertTrue(audits.size() > 0);
        assertTrue(audits.stream().allMatch(a -> a.getAction().equals("PAYMENT_COMPLETED")));
    }

    @Test
    @DisplayName("Should find audit records by new status")
    void testFindByNewStatus() {
        PaymentAudit audit = new PaymentAudit(
            "TEST-AUDIT-TXN-004",
            "PAYMENT_FAILED",
            PaymentStatus.PROCESSING,
            PaymentStatus.FRAUD_CHECK_FAILED,
            "ACC001",
            "ACC002",
            new BigDecimal("10000.00"),
            "USD",
            "SYSTEM",
            "Fraud detected"
        );
        auditRepository.save(audit);

        List<PaymentAudit> audits = auditRepository.findByNewStatus(PaymentStatus.FRAUD_CHECK_FAILED);

        assertNotNull(audits);
        assertTrue(audits.size() > 0);
        assertTrue(audits.stream().allMatch(a -> a.getNewStatus() == PaymentStatus.FRAUD_CHECK_FAILED));
    }

    @Test
    @DisplayName("Should find audit records by account (from or to)")
    void testFindByAccount() {
        PaymentAudit audit1 = new PaymentAudit(
            "TEST-AUDIT-TXN-005",
            "PAYMENT_CREATED",
            null,
            PaymentStatus.PENDING,
            "ACC999",
            "ACC002",
            new BigDecimal("750.00"),
            "USD",
            "SYSTEM",
            "Payment from ACC999"
        );
        auditRepository.save(audit1);

        PaymentAudit audit2 = new PaymentAudit(
            "TEST-AUDIT-TXN-006",
            "PAYMENT_CREATED",
            null,
            PaymentStatus.PENDING,
            "ACC001",
            "ACC999",
            new BigDecimal("850.00"),
            "USD",
            "SYSTEM",
            "Payment to ACC999"
        );
        auditRepository.save(audit2);

        List<PaymentAudit> audits = auditRepository.findByAccount("ACC999");

        assertNotNull(audits);
        assertTrue(audits.size() >= 2);
        assertTrue(audits.stream().allMatch(a -> 
            "ACC999".equals(a.getFromAccount()) || "ACC999".equals(a.getToAccount())
        ));
    }

    @Test
    @DisplayName("Should find audit records by date range")
    void testFindByAuditTimestampBetween() {
        LocalDateTime now = LocalDateTime.now();
        LocalDateTime oneHourAgo = now.minusHours(1);
        LocalDateTime oneHourLater = now.plusHours(1);

        PaymentAudit audit = new PaymentAudit(
            "TEST-AUDIT-TXN-007",
            "PAYMENT_CREATED",
            null,
            PaymentStatus.PENDING,
            "ACC001",
            "ACC002",
            new BigDecimal("300.00"),
            "USD",
            "SYSTEM",
            "Recent payment"
        );
        auditRepository.save(audit);

        List<PaymentAudit> audits = auditRepository.findByAuditTimestampBetween(oneHourAgo, oneHourLater);

        assertNotNull(audits);
        assertTrue(audits.size() > 0);
        assertTrue(audits.stream().allMatch(a -> 
            a.getAuditTimestamp().isAfter(oneHourAgo) && a.getAuditTimestamp().isBefore(oneHourLater)
        ));
    }

    @Test
    @DisplayName("Should find recent audit records with limit")
    void testFindRecentAudits() {
        // Create several audit records
        for (int i = 0; i < 5; i++) {
            PaymentAudit audit = new PaymentAudit(
                "TEST-AUDIT-TXN-RECENT-" + i,
                "PAYMENT_CREATED",
                null,
                PaymentStatus.PENDING,
                "ACC001",
                "ACC002",
                new BigDecimal("100.00"),
                "USD",
                "SYSTEM",
                "Recent audit " + i
            );
            auditRepository.save(audit);
        }

        List<PaymentAudit> audits = auditRepository.findRecentAudits(3);

        assertNotNull(audits);
        assertTrue(audits.size() <= 3);
    }

    @Test
    @DisplayName("Should handle status change audit correctly")
    void testStatusChangeAudit() {
        PaymentAudit audit = new PaymentAudit(
            "TEST-AUDIT-TXN-008",
            "STATUS_CHANGE",
            PaymentStatus.PENDING,
            PaymentStatus.COMPLETED,
            "ACC001",
            "ACC002",
            new BigDecimal("1234.56"),
            "USD",
            "SYSTEM",
            "Status changed from PENDING to COMPLETED"
        );

        PaymentAudit saved = auditRepository.save(audit);

        assertNotNull(saved.getId());
        assertEquals(PaymentStatus.PENDING, saved.getOldStatus());
        assertEquals(PaymentStatus.COMPLETED, saved.getNewStatus());
        assertEquals("STATUS_CHANGE", saved.getAction());
    }

    @Test
    @DisplayName("Should handle audit with null old status (creation)")
    void testAuditWithNullOldStatus() {
        PaymentAudit audit = new PaymentAudit(
            "TEST-AUDIT-TXN-009",
            "PAYMENT_CREATED",
            null,
            PaymentStatus.PENDING,
            "ACC001",
            "ACC002",
            new BigDecimal("999.99"),
            "USD",
            "SYSTEM",
            "Initial payment creation"
        );

        PaymentAudit saved = auditRepository.save(audit);

        assertNotNull(saved.getId());
        assertNull(saved.getOldStatus());
        assertEquals(PaymentStatus.PENDING, saved.getNewStatus());
    }

    @Test
    @DisplayName("Should handle decimal amounts correctly in audit")
    void testDecimalAmountsInAudit() {
        PaymentAudit audit = new PaymentAudit(
            "TEST-AUDIT-TXN-010",
            "PAYMENT_CREATED",
            null,
            PaymentStatus.PENDING,
            "ACC001",
            "ACC002",
            new BigDecimal("1234.56"),
            "USD",
            "SYSTEM",
            "Decimal amount test"
        );

        auditRepository.save(audit);

        List<PaymentAudit> audits = auditRepository.findByTransactionId("TEST-AUDIT-TXN-010");
        assertTrue(audits.size() > 0);
        assertEquals(new BigDecimal("1234.56"), audits.get(0).getAmount());
    }

    @Test
    @DisplayName("Should handle different performers in audit")
    void testDifferentPerformers() {
        PaymentAudit audit1 = new PaymentAudit(
            "TEST-AUDIT-TXN-011",
            "PAYMENT_CREATED",
            null,
            PaymentStatus.PENDING,
            "ACC001",
            "ACC002",
            new BigDecimal("500.00"),
            "USD",
            "SYSTEM",
            "System initiated payment"
        );
        auditRepository.save(audit1);

        PaymentAudit audit2 = new PaymentAudit(
            "TEST-AUDIT-TXN-012",
            "PAYMENT_CREATED",
            null,
            PaymentStatus.PENDING,
            "ACC001",
            "ACC002",
            new BigDecimal("600.00"),
            "USD",
            "USER123",
            "User initiated payment"
        );
        auditRepository.save(audit2);

        List<PaymentAudit> systemAudits = auditRepository.findByTransactionId("TEST-AUDIT-TXN-011");
        List<PaymentAudit> userAudits = auditRepository.findByTransactionId("TEST-AUDIT-TXN-012");

        assertEquals("SYSTEM", systemAudits.get(0).getPerformedBy());
        assertEquals("USER123", userAudits.get(0).getPerformedBy());
    }

    @Test
    @DisplayName("Should verify audit timestamp is set automatically")
    void testAuditTimestampAutoSet() {
        LocalDateTime beforeSave = LocalDateTime.now().minusSeconds(1);
        
        PaymentAudit audit = new PaymentAudit(
            "TEST-AUDIT-TXN-013",
            "PAYMENT_CREATED",
            null,
            PaymentStatus.PENDING,
            "ACC001",
            "ACC002",
            new BigDecimal("777.77"),
            "USD",
            "SYSTEM",
            "Timestamp test"
        );

        PaymentAudit saved = auditRepository.save(audit);
        LocalDateTime afterSave = LocalDateTime.now().plusSeconds(1);

        assertNotNull(saved.getAuditTimestamp());
        assertTrue(saved.getAuditTimestamp().isAfter(beforeSave));
        assertTrue(saved.getAuditTimestamp().isBefore(afterSave));
    }

    @Test
    @DisplayName("Should handle empty result sets for non-existent data")
    void testEmptyResultSets() {
        List<PaymentAudit> audits = auditRepository.findByTransactionId("NON-EXISTENT-TXN");
        
        assertNotNull(audits);
        assertTrue(audits.isEmpty());
    }

    @Test
    @DisplayName("Should handle long details text in audit")
    void testLongDetailsText() {
        String longDetails = "This is a very long details text that contains extensive information about the payment audit. ".repeat(10);
        
        PaymentAudit audit = new PaymentAudit(
            "TEST-AUDIT-TXN-014",
            "PAYMENT_CREATED",
            null,
            PaymentStatus.PENDING,
            "ACC001",
            "ACC002",
            new BigDecimal("123.45"),
            "USD",
            "SYSTEM",
            longDetails
        );

        PaymentAudit saved = auditRepository.save(audit);

        assertNotNull(saved.getId());
        assertEquals(longDetails, saved.getDetails());
    }

    @Test
    @DisplayName("Should maintain audit trail order for transaction")
    void testAuditTrailOrder() {
        String txnId = "TEST-AUDIT-TXN-015";
        
        // Create audit trail with explicit timestamps to ensure ordering
        LocalDateTime timestamp1 = LocalDateTime.now();
        PaymentAudit audit1 = new PaymentAudit(txnId, "PAYMENT_CREATED", null, PaymentStatus.PENDING,
            "ACC001", "ACC002", new BigDecimal("100.00"), "USD", "SYSTEM", "Created");
        audit1.setAuditTimestamp(timestamp1);
        auditRepository.save(audit1);
        
        LocalDateTime timestamp2 = timestamp1.plusSeconds(1);
        PaymentAudit audit2 = new PaymentAudit(txnId, "STATUS_CHANGE", PaymentStatus.PENDING, PaymentStatus.PROCESSING,
            "ACC001", "ACC002", new BigDecimal("100.00"), "USD", "SYSTEM", "Processing");
        audit2.setAuditTimestamp(timestamp2);
        auditRepository.save(audit2);
        
        LocalDateTime timestamp3 = timestamp1.plusSeconds(2);
        PaymentAudit audit3 = new PaymentAudit(txnId, "PAYMENT_COMPLETED", PaymentStatus.PROCESSING, PaymentStatus.COMPLETED,
            "ACC001", "ACC002", new BigDecimal("100.00"), "USD", "SYSTEM", "Completed");
        audit3.setAuditTimestamp(timestamp3);
        auditRepository.save(audit3);

        List<PaymentAudit> audits = auditRepository.findByTransactionId(txnId);

        assertEquals(3, audits.size());
    }
}
